FROM node:lts-alpine AS build
WORKDIR /app

COPY *.json .
RUN npm i

COPY vite.config.ts . 
COPY index.html .
COPY public public 

COPY src src
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html