services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "4200:4200"
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      JWT_SECRET: ${JWT_SECRET}

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER} 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./persist/database:/var/lib/postgresql

  nginx:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    depends_on:
      - backend
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/032025-bleu-6.wns.wilders.dev:/etc/letsencrypt/live/032025-bleu-6.wns.wilders.dev:ro
      - ./logs:/var/log/nginx
      
volumes:
  postgres-data: