events {}

http {
  include mime.types;

  server {
    listen 443 ssl;
    server_name 032025-bleu-6.wns.wilders.dev;

    ssl_certificate /etc/letsencrypt/live/032025-bleu-6.wns.wilders.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/032025-bleu-6.wns.wilders.dev/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location /hooks {
      proxy_pass http://127.0.0.1:9000/hooks/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /graphql {
      proxy_pass http://backend:4200;
    }

    location / {
      root /usr/share/nginx/html;
      index index.html;
      try_files $uri /index.html;
    }
  }
}